//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabiMall.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BabiMallEntities : DbContext
    {
        public BabiMallEntities()
            : base("name=BabiMallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUDEMATBANG> CHUDEMATBANGs { get; set; }
        public virtual DbSet<CTTHAMDO> CTTHAMDOes { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<QUANLY> QUANLies { get; set; }
        public virtual DbSet<SUKIEN> SUKIENs { get; set; }
        public virtual DbSet<CTTHUEMATBANG> CTTHUEMATBANGs { get; set; }
        public virtual DbSet<MATBANG> MATBANGs { get; set; }
        public virtual DbSet<DONTHUEMATBANG> DONTHUEMATBANGs { get; set; }
        public virtual DbSet<DANHMUC> DANHMUCs { get; set; }
    }
}
