//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabiMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTHUEMATBANG
    {
        public int Somatbang { get; set; }
        public int Mamatbang { get; set; }
        public Nullable<int> Sodientichthue { get; set; }
        public Nullable<decimal> Dongia { get; set; }
        public Nullable<decimal> Thanhtien { get; set; }
        public string Hinhminhhoa { get; set; }
        public Nullable<decimal> Tongdoanhthu { get; set; }
    
        public virtual MATBANG MATBANG { get; set; }
        public virtual DONTHUEMATBANG DONTHUEMATBANG { get; set; }
    }
}
