//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabiMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUC
    {
        public int ID { get; set; }
        public string Tendanhmuc { get; set; }
        public string Mota { get; set; }
        public string Hinhminhhoa { get; set; }
        public string Loaidoanhmuc { get; set; }
    }
}
