//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabiMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATBANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATBANG()
        {
            this.CTTHUEMATBANGs = new HashSet<CTTHUEMATBANG>();
        }
    
        public int Mamatbang { get; set; }
        public string Thongtinmatbang { get; set; }
        public string Donvitinh { get; set; }
        public Nullable<decimal> Dongia { get; set; }
        public string Mota { get; set; }
        public string Tenmatbang { get; set; }
        public string Vitri { get; set; }
        public string Dientich { get; set; }
        public string Dienthoai { get; set; }
        public string Lienhe { get; set; }
        public string Hinhminhhoa { get; set; }
        public Nullable<int> MaCD { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongban { get; set; }
        public Nullable<int> solanxem { get; set; }
        public string Trangthaidonhang { get; set; }
    
        public virtual CHUDEMATBANG CHUDEMATBANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTHUEMATBANG> CTTHUEMATBANGs { get; set; }
    }
}
