//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabiMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUANLY
    {
        public int Maquanly { get; set; }
        public string Tendangnhap { get; set; }
        public string Matkhau { get; set; }
        public string Tenquanli { get; set; }
    }
}
