//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabiMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUKIEN
    {
        public int MaSK { get; set; }
        public string TenSK { get; set; }
        public Nullable<System.DateTime> Ngaybatdau { get; set; }
        public string Thongtinsukien { get; set; }
        public string Motasukien { get; set; }
        public string Anhsukien { get; set; }
    }
}
